[package]
name = "monkey"
version = "0.1.0"
authors = ["Dean Strelau <dean@strelau.net>"]
edition = "2018"

[dependencies]
unicode-segmentation = "1.3.0"

[lib]
name = "monkey"
path = "src/lib.rs"

[[bin]]
name = "monkey"
path = "src/main.rs"
